'use client';

import { useState } from 'react';
import Header from '@/components/Header';
import Link from 'next/link';
import { User } from '@/types';

const mockUser: User = {
  id: '1',
  name: 'Ryan Manitoba',
  email: 'ryan.manitoba@company.com',
  role: 'manager',
  department: 'Legal',
};

interface LLCFormData {
  entityName: string;
  homeState: string;
  qualifyStates: string;
  internalOwner: string;
  businessPurpose: string;
}

export default function CreateLLCPage() {
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState<LLCFormData>({
    entityName: '',
    homeState: '',
    qualifyStates: '',
    internalOwner: mockUser.name,
    businessPurpose: '',
  });
  const [showDocument, setShowDocument] = useState(false);
  const [documentContent, setDocumentContent] = useState('');
  const [showEmailPrompt, setShowEmailPrompt] = useState(false);

  const generateDocumentContent = (data: LLCFormData) => {
    const today = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

    return `LLC FORMATION REQUEST

Date: ${today}
Entity Name: ${data.entityName}
Formation State: ${data.homeState}

ENTITY INFORMATION

Legal Name: ${data.entityName}
Type: Limited Liability Company (LLC)
Home State: ${data.homeState}
Foreign Qualification States: ${data.qualifyStates}

INTERNAL INFORMATION

Internal Owner: ${data.internalOwner}
Business Purpose: ${data.businessPurpose}

FILING INSTRUCTIONS

Please proceed with the following:

1. Form LLC in ${data.homeState}
2. Foreign qualify in: ${data.qualifyStates}
3. Obtain registered agent service in all applicable states
4. File all necessary documents with state authorities
5. Provide copies of:
   - Articles of Organization
   - Certificate of Formation
   - EIN documentation
   - Foreign qualification certificates

CONTACT INFORMATION

Primary Contact: ${data.internalOwner}
Legal Department
Company Legal Operations

---

This document was generated by LegalCore LLC Formation System
${today}`;
  };

  const handleNext = () => {
    if (step === 5) {
      // Generate document
      const content = generateDocumentContent(formData);
      setDocumentContent(content);
      setShowDocument(true);
    } else {
      setStep(step + 1);
    }
  };

  const handleBack = () => {
    if (step > 1) {
      setStep(step - 1);
    }
  };

  const canProceed = () => {
    switch (step) {
      case 1:
        return formData.entityName.trim() !== '';
      case 2:
        return formData.homeState.trim() !== '';
      case 3:
        return formData.qualifyStates.trim() !== '';
      case 4:
        return formData.internalOwner.trim() !== '';
      case 5:
        return formData.businessPurpose.trim() !== '';
      default:
        return false;
    }
  };

  const handleDownloadDocument = () => {
    const blob = new Blob([documentContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${formData.entityName}_Formation_Request.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const handleSendToCSC = () => {
    const emailSubject = `LLC Formation Request - ${formData.entityName}`;
    const emailBody = `Hi Dave,%0D%0A%0D%0ACan you please file this in ${formData.homeState}. We will want to qualify in ${formData.qualifyStates}.%0D%0A%0D%0AThank you,%0D%0A${formData.internalOwner}`;

    const mailtoLink = `mailto:dave.nickelsen@cscglobal.com?subject=${encodeURIComponent(emailSubject)}&body=${emailBody}`;
    window.location.href = mailtoLink;

    setShowEmailPrompt(false);
  };

  const renderStep = () => {
    switch (step) {
      case 1:
        return (
          <div className="space-y-6">
            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-2">What's the entity name?</h2>
              <p className="text-gray-600">Enter the legal name for your new LLC</p>
            </div>
            <div>
              <label htmlFor="entityName" className="block text-sm font-semibold text-gray-700 mb-2">
                Entity Name
              </label>
              <input
                id="entityName"
                type="text"
                value={formData.entityName}
                onChange={(e) => setFormData({ ...formData, entityName: e.target.value })}
                placeholder="e.g., TechCorp Solutions LLC"
                className="w-full rounded-lg border border-gray-300 px-4 py-3 text-gray-900 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                autoFocus
              />
            </div>
          </div>
        );

      case 2:
        return (
          <div className="space-y-6">
            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-2">What state do you want to incorporate in?</h2>
              <p className="text-gray-600">This is your home state for formation</p>
            </div>
            <div>
              <label htmlFor="homeState" className="block text-sm font-semibold text-gray-700 mb-2">
                Home State
              </label>
              <select
                id="homeState"
                value={formData.homeState}
                onChange={(e) => setFormData({ ...formData, homeState: e.target.value })}
                className="w-full rounded-lg border border-gray-300 px-4 py-3 text-gray-900 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                autoFocus
              >
                <option value="">Select a state...</option>
                <option value="Delaware">Delaware</option>
                <option value="California">California</option>
                <option value="New York">New York</option>
                <option value="Texas">Texas</option>
                <option value="Florida">Florida</option>
                <option value="Nevada">Nevada</option>
                <option value="Wyoming">Wyoming</option>
                <option value="Other">Other</option>
              </select>
            </div>
          </div>
        );

      case 3:
        return (
          <div className="space-y-6">
            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-2">What states will you be operating in?</h2>
              <p className="text-gray-600">List states where you need foreign qualification</p>
            </div>
            <div>
              <label htmlFor="qualifyStates" className="block text-sm font-semibold text-gray-700 mb-2">
                Qualification States
              </label>
              <input
                id="qualifyStates"
                type="text"
                value={formData.qualifyStates}
                onChange={(e) => setFormData({ ...formData, qualifyStates: e.target.value })}
                placeholder="e.g., California, New York, Texas"
                className="w-full rounded-lg border border-gray-300 px-4 py-3 text-gray-900 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                autoFocus
              />
              <p className="mt-2 text-sm text-gray-500">Separate multiple states with commas</p>
            </div>
          </div>
        );

      case 4:
        return (
          <div className="space-y-6">
            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-2">Who will be the internal owner?</h2>
              <p className="text-gray-600">Assign an internal team member to manage this entity</p>
            </div>
            <div>
              <label htmlFor="internalOwner" className="block text-sm font-semibold text-gray-700 mb-2">
                Internal Owner
              </label>
              <input
                id="internalOwner"
                type="text"
                value={formData.internalOwner}
                onChange={(e) => setFormData({ ...formData, internalOwner: e.target.value })}
                placeholder="e.g., Ryan Manitoba"
                className="w-full rounded-lg border border-gray-300 px-4 py-3 text-gray-900 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                autoFocus
              />
            </div>
          </div>
        );

      case 5:
        return (
          <div className="space-y-6">
            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-2">What's the business purpose?</h2>
              <p className="text-gray-600">Describe the internal business purpose for this entity</p>
            </div>
            <div>
              <label htmlFor="businessPurpose" className="block text-sm font-semibold text-gray-700 mb-2">
                Business Purpose
              </label>
              <textarea
                id="businessPurpose"
                value={formData.businessPurpose}
                onChange={(e) => setFormData({ ...formData, businessPurpose: e.target.value })}
                placeholder="e.g., Software development and consulting services for enterprise clients"
                rows={4}
                className="w-full rounded-lg border border-gray-300 px-4 py-3 text-gray-900 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                autoFocus
              />
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  if (showDocument) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
        <Header user={mockUser} />

        <main className="mx-auto max-w-4xl px-6 py-12">
          <div className="mb-8">
            <Link
              href="/modules/entity-management"
              className="inline-flex items-center gap-2 text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
              </svg>
              Back to Entity Management
            </Link>
          </div>

          <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
            {/* Header */}
            <div className="bg-gradient-to-r from-blue-600 to-blue-700 p-6 text-white">
              <h1 className="text-2xl font-bold">LLC Formation Document</h1>
              <p className="text-sm text-blue-100 mt-1">Review and edit before sending to CSC</p>
            </div>

            {/* Document Content */}
            <div className="p-6">
              <textarea
                value={documentContent}
                onChange={(e) => setDocumentContent(e.target.value)}
                className="min-h-[500px] w-full rounded-lg border border-gray-300 p-4 font-mono text-sm text-gray-900 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                spellCheck={false}
              />
            </div>

            {/* Actions */}
            <div className="border-t border-gray-200 bg-gray-50 p-6">
              <div className="flex items-center justify-between gap-4">
                <button
                  onClick={handleDownloadDocument}
                  className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-6 py-3 text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-50"
                >
                  <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  Download Document
                </button>
                <button
                  onClick={() => setShowEmailPrompt(true)}
                  className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-blue-700"
                >
                  <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                  </svg>
                  Send to CSC
                </button>
              </div>
            </div>
          </div>

          {/* Email Confirmation Modal */}
          {showEmailPrompt && (
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-6">
              <div className="w-full max-w-md rounded-lg bg-white p-6 shadow-xl">
                <h3 className="mb-4 text-lg font-bold text-gray-900">Send to CSC?</h3>
                <div className="mb-6 space-y-3 rounded-lg bg-gray-50 p-4 text-sm">
                  <div>
                    <span className="font-semibold text-gray-700">To:</span>
                    <p className="text-gray-900">dave.nickelsen@cscglobal.com</p>
                  </div>
                  <div>
                    <span className="font-semibold text-gray-700">Subject:</span>
                    <p className="text-gray-900">LLC Formation Request - {formData.entityName}</p>
                  </div>
                  <div>
                    <span className="font-semibold text-gray-700">Message:</span>
                    <p className="text-gray-900">
                      Hi Dave,<br /><br />
                      Can you please file this in {formData.homeState}. We will want to qualify in {formData.qualifyStates}.<br /><br />
                      Thank you,<br />
                      {formData.internalOwner}
                    </p>
                  </div>
                </div>
                <div className="flex gap-3">
                  <button
                    onClick={() => setShowEmailPrompt(false)}
                    className="flex-1 rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-50"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleSendToCSC}
                    className="flex-1 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-blue-700"
                  >
                    Open Email Client
                  </button>
                </div>
              </div>
            </div>
          )}
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
      <Header user={mockUser} />

      <main className="mx-auto max-w-3xl px-6 py-12">
        <div className="mb-8">
          <Link
            href="/modules/entity-management"
            className="inline-flex items-center gap-2 text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Back to Entity Management
          </Link>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
          {/* Header */}
          <div className="bg-gradient-to-r from-blue-600 to-blue-700 p-6 text-white">
            <h1 className="text-2xl font-bold">Create New LLC</h1>
            <p className="text-sm text-blue-100 mt-1">Answer a few questions to generate your formation request</p>
          </div>

          {/* Progress Indicator */}
          <div className="border-b border-gray-200 bg-gray-50 p-6">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium text-gray-700">Step {step} of 5</span>
              <span className="text-sm text-gray-500">{Math.round((step / 5) * 100)}% Complete</span>
            </div>
            <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
              <div
                className="h-full bg-blue-600 transition-all duration-300"
                style={{ width: `${(step / 5) * 100}%` }}
              />
            </div>
          </div>

          {/* Form Content */}
          <div className="p-8">
            {renderStep()}
          </div>

          {/* Navigation */}
          <div className="border-t border-gray-200 bg-gray-50 p-6">
            <div className="flex items-center justify-between gap-4">
              <button
                onClick={handleBack}
                disabled={step === 1}
                className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-6 py-3 text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
              >
                <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
                Back
              </button>
              <button
                onClick={handleNext}
                disabled={!canProceed()}
                className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {step === 5 ? 'Generate Document' : 'Continue'}
                <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
