'use client';

import { useState } from 'react';

interface LLCData {
  homeState: string;
  qualifyStates: string;
  internalOwner: string;
  businessPurpose: string;
  entityName?: string;
}

interface LLCDocumentGeneratorProps {
  llcData: LLCData;
  onClose: () => void;
}

export default function LLCDocumentGenerator({ llcData, onClose }: LLCDocumentGeneratorProps) {
  const [entityName, setEntityName] = useState(llcData.entityName || '');
  const [documentContent, setDocumentContent] = useState(generateDocumentContent(llcData, llcData.entityName || '[Entity Name]'));
  const [showEmailPrompt, setShowEmailPrompt] = useState(false);

  function generateDocumentContent(data: LLCData, name: string) {
    const today = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

    return `LLC FORMATION REQUEST

Date: ${today}
Entity Name: ${name}
Formation State: ${data.homeState}

ENTITY INFORMATION

Legal Name: ${name}
Type: Limited Liability Company (LLC)
Home State: ${data.homeState}
Foreign Qualification States: ${data.qualifyStates}

INTERNAL INFORMATION

Internal Owner: ${data.internalOwner}
Business Purpose: ${data.businessPurpose}

FILING INSTRUCTIONS

Please proceed with the following:

1. Form LLC in ${data.homeState}
2. Foreign qualify in: ${data.qualifyStates}
3. Obtain registered agent service in all applicable states
4. File all necessary documents with state authorities
5. Provide copies of:
   - Articles of Organization
   - Certificate of Formation
   - EIN documentation
   - Foreign qualification certificates

CONTACT INFORMATION

Primary Contact: ${data.internalOwner}
Legal Department
Company Legal Operations

---

This document was generated by LegalCore LLC Formation System
${today}`;
  }

  const handleEntityNameChange = (newName: string) => {
    setEntityName(newName);
    setDocumentContent(generateDocumentContent(llcData, newName || '[Entity Name]'));
  };

  const handleSendToCSC = () => {
    setShowEmailPrompt(true);
  };

  const handleEmailSend = () => {
    const emailSubject = `LLC Formation Request - ${entityName || 'New LLC'}`;
    const emailBody = `Hi Dave,%0D%0A%0D%0ACan you please file this in ${llcData.homeState}. We will want to qualify in ${llcData.qualifyStates}.%0D%0A%0D%0AThank you,%0D%0A${llcData.internalOwner}`;

    // Create mailto link
    const mailtoLink = `mailto:dave.nickelsen@cscglobal.com?subject=${encodeURIComponent(emailSubject)}&body=${emailBody}`;

    // Open email client
    window.location.href = mailtoLink;

    // Close the document generator after a delay
    setTimeout(() => {
      onClose();
    }, 1000);
  };

  const handleDownloadPDF = () => {
    // Create a blob with the document content
    const blob = new Blob([documentContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${entityName || 'LLC'}_Formation_Request.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/50 p-4">
      <div className="relative max-h-[90vh] w-full max-w-4xl overflow-hidden rounded-xl bg-white shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-gray-200 bg-gradient-to-r from-blue-600 to-blue-700 p-6 text-white">
          <div>
            <h2 className="text-2xl font-bold">LLC Formation Document</h2>
            <p className="text-sm text-blue-100">Review and edit before sending</p>
          </div>
          <button
            onClick={onClose}
            className="rounded-full p-2 transition-colors hover:bg-white/10"
            aria-label="Close document generator"
          >
            <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Entity Name Input */}
        <div className="border-b border-gray-200 bg-gray-50 p-6">
          <label className="mb-2 block text-sm font-semibold text-gray-700">
            Entity Name
          </label>
          <input
            type="text"
            value={entityName}
            onChange={(e) => handleEntityNameChange(e.target.value)}
            placeholder="Enter LLC name (e.g., TechCorp Solutions LLC)"
            className="w-full rounded-lg border border-gray-300 px-4 py-3 text-gray-900 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
          />
        </div>

        {/* Document Content */}
        <div className="max-h-[50vh] overflow-y-auto p-6">
          <textarea
            value={documentContent}
            onChange={(e) => setDocumentContent(e.target.value)}
            className="min-h-[400px] w-full rounded-lg border border-gray-300 p-4 font-mono text-sm text-gray-900 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
            spellCheck={false}
          />
        </div>

        {/* Actions */}
        <div className="border-t border-gray-200 bg-gray-50 p-6">
          <div className="flex items-center justify-between gap-4">
            <button
              onClick={handleDownloadPDF}
              className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-6 py-3 text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-50"
            >
              <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Download Document
            </button>
            <button
              onClick={handleSendToCSC}
              disabled={!entityName.trim()}
              className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
            >
              <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              Send to CSC
            </button>
          </div>
        </div>

        {/* Email Confirmation Modal */}
        {showEmailPrompt && (
          <div className="absolute inset-0 flex items-center justify-center bg-black/50 p-6">
            <div className="w-full max-w-md rounded-lg bg-white p-6 shadow-xl">
              <h3 className="mb-4 text-lg font-bold text-gray-900">Send to CSC?</h3>
              <div className="mb-6 space-y-3 rounded-lg bg-gray-50 p-4 text-sm">
                <div>
                  <span className="font-semibold text-gray-700">To:</span>
                  <p className="text-gray-900">dave.nickelsen@cscglobal.com</p>
                </div>
                <div>
                  <span className="font-semibold text-gray-700">Subject:</span>
                  <p className="text-gray-900">LLC Formation Request - {entityName}</p>
                </div>
                <div>
                  <span className="font-semibold text-gray-700">Message:</span>
                  <p className="text-gray-900">
                    Hi Dave,<br /><br />
                    Can you please file this in {llcData.homeState}. We will want to qualify in {llcData.qualifyStates}.<br /><br />
                    Thank you,<br />
                    {llcData.internalOwner}
                  </p>
                </div>
              </div>
              <div className="flex gap-3">
                <button
                  onClick={() => setShowEmailPrompt(false)}
                  className="flex-1 rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  onClick={handleEmailSend}
                  className="flex-1 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-blue-700"
                >
                  Open Email Client
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
